### ISSUE TITLE
Dar does not read config file from /etc

### ISSUE THREAD

**Issue by RA-Kooi** [Edrusb/DAR#22] opened 2020-09-22 06:53 UTC
**Describe the bug**
`/etc/darrc` is not being read, instead dar tries to read `/darrc`.
`DAR_SYS_DIR` is empty, reading the autotools files I see `system_path` is used, I tried googling this, but did not find any information on this. I assume it's an internal option to autotools.
`system_path` looks to be empty in the version of autotools used to make the release tarball.

As a workaround I manually patched the final makefile to use `/etc` hardcoded as I do not know how autotools works.

**To Reproduce**
1. Fetch the latest tarball.
2. Build dar with any option.

**Expected behavior**
Read `darrc` from the `/etc` folder.

**Software used:**
- which dar/libdar version has been used: dar 2.6.12
- how it has been obtained or compiled: https://aur.archlinux.org/packages/dar/
```
Warning: using insecure memory!

 lt-dar version 2.6.12, Copyright (C) 2002-2020 Denis Corbin
   Long options support         : YES

 Using libdar 6.2.6 built with compilation time options:
   Libz compression (gzip)      : YES
   Libbz2 compression (bzip2)   : YES
   Liblzo2 compression (lzo)    : YES
   Liblzma compression (xz)     : YES
   Strong encryption (libgcrypt): YES
   Public key ciphers (gpgme)   : YES
   Extended Attributes support  : YES
   Large files support (> 2GB)  : YES
   ext2fs NODUMP flag support   : YES
   Integer size used            : 64 bits
   Thread safe support          : YES
   Furtive read mode support    : YES
   Linux ext2/3/4 FSA support   : YES
   Mac OS X HFS+ FSA support    : NO
   Detected system/CPU endian   : little
   Posix fadvise support        : YES
   Large dir. speed optimi.     : YES
   Timestamp read accuracy      : 1 microsecond
   Timestamp write accuracy     : 1 microsecond
   Restores dates of symlinks   : YES
   Multiple threads (libthreads): NO 
   Delta compression support    : NO
   Remote repository support    : NO

 compiled the Sep 22 2020 with GNUC version 10.1.0
 lt-dar is part of the Disk ARchive suite (Release 2.6.12)
 lt-dar comes with ABSOLUTELY NO WARRANTY; for details
 type `lt-dar -W'. This is free software, and you are welcome
 to redistribute it under certain conditions; type `lt-dar -L | more'
 for details.
```

**Operating system used:**
Arch Linux

**Comment by Edrusb** [comment] 2020-09-26 11:36
Hello,

thanks for your feedback, the problem is fixed in release candidate 1 for 2.6.13 which is available either on git / branch_2.6.x or as a tarball from [https://dar.dm3c.org/dar.linux.free.fr/Interim_releases/](https://dar.dm3c.org/dar.linux.free.fr/Interim_releases/)

Cheers,
Denis

**Closed** 2020-11-26 20:15 UTC
Labels: bug
